name: Build rufus

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Checkout rufus
        uses: actions/checkout@v4
        with:
          repository: curl/curl
          ref: refs/tags/curl-7_79_1
          path: curl

      - name: Setup msvc
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64
          toolset: 14.29
          sdk: 10.0.19041.0

      - name: Modify
        run: |
          (Get-Content ".\curl\winbuild\MakefileBuild.vc" -Raw) `
            -replace "/O2", "/Os" `
            -replace "CFLAGS     =", "CFLAGS     = /arch:AVX2 /MD /MP /Oi /Os /Gy /GL /Gw /fp:fast /GR- /GS-" | `
            Set-Content ".\curl\winbuild\MakefileBuild.vc"

          (Get-Content ".\curl\src\tool_hugehelp.c.cvs" -Raw) `
              -replace 'puts("This is a silly replacement for the actual file.");', ' ' | Set-Content ".\curl\src\tool_hugehelp.c"

      - name: Build
        working-directory: curl\winbuild
        run: |
          nmake /NOLOGO /f Makefile.vc mode=dll

      - name: Archive binary
        uses: actions/upload-artifact@v4
        with:
          name: rufus
          path: |
            rufus/x64/Release/rufus.exe
