name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Checkout self
        uses: actions/checkout@v6

      - name: Checkout curl
        run: |
          curl.exe -L -o curl.zip "https://curl.se/download/curl-7.88.1.zip"
          Expand-Archive -Path "curl.zip" -DestinationPath "."
          Rename-Item -Path "curl-7.79.1" -NewName "curl"

      - name: Setup msvc
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64
          toolset: 14.29
          sdk: 10.0.19041.0

      - name: Modify
        run: |
          (Get-Content ".\curl\winbuild\MakefileBuild.vc" -Raw) `
            -replace "/O2", "/Os" `
            -replace "CFLAGS      =", "CFLAGS      = /arch:AVX2 /MD /MP /Oi /Os /Gy /GL /Gw /fp:fast /GR- /GS-" `
            -replace "LFLAGS     =", "LFLAGS     = /LTCG /MANIFEST:NO /MERGE:_RDATA=.rdata /OPT:REF /OPT:ICF" | `
            Set-Content ".\curl\winbuild\MakefileBuild.vc"

          Move-Item -Path "tool_hugehelp.c" -Destination ".\curl\src\tool_hugehelp.c" -Force

      - name: Build
        working-directory: curl\winbuild
        run: |
          nmake /NOLOGO /f Makefile.vc mode=dll

      - name: Archive
        uses: actions/upload-artifact@v5
        with:
          name: curl
          path: |
            curl/builds/
