name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Checkout self
        uses: actions/checkout@v6

      - name: Checkout curl
        run: |
          curl.exe -L -o curl.zip "https://curl.se/download/curl-7.88.1.zip"
          Expand-Archive -Path "curl.zip" -DestinationPath "."
          Rename-Item -Path "curl-7.88.1" -NewName "curl"

      - name: Setup msvc
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64
          toolset: 14.29
          sdk: 10.0.19041.0

      - name: Modify
        run: |
          Move-Item -Path "tool_hugehelp.c" -Destination ".\curl\src\tool_hugehelp.c" -Force


      - name: Remove res file
        working-directory: curl/winbuild
        shell: pwsh
        run: |
          $content = Get-Content -Path "MakefileBuild.vc" -Raw -Encoding UTF8

          # 1. 禁用 libcurl.res 和 curl.res 的生成
          $content = $content -replace '\$\(RESOURCE\)', ''
          $content = $content -replace '\$\(CURL_DIROBJ\)\\curl\.res', ''

          # 2. 强制不调用 rc.exe
          $content = $content -replace 'RC\s*=\s*rc\.exe', 'RC = echo rc disabled'

          # 3. 移除 manifest 处理（MANIFESTTOOL）
          $content = $content -replace '\$\(MANIFESTTOOL\)', 'echo manifest disabled'

          # 4. 在链接 curl.exe 时不带资源
          $content = $content -replace 'EXE_OBJS = .*', 'EXE_OBJS = $(CURL_FROM_LIBCURL)'

          Set-Content -Path "MakefileBuild.vc" -Value $content -Encoding UTF8
          Write-Host "Makefile.vc patched to disable resources"
      
      - name: Build
        working-directory: curl/winbuild
        shell: pwsh
        run: |
          nmake /NOLOGO /f Makefile.vc MODE=dll `
          CFLAGS="/arch:AVX2 /MD /MP /Oi /Os /Gy /GL /Gw /fp:fast /GR- /GS-" `
          LFLAGS="/LTCG /MANIFEST:NO /MERGE:_RDATA=.rdata /OPT:REF /OPT:ICF" `
          LDFLAGS="/LTCG /MANIFEST:NO /MERGE:_RDATA=.rdata /OPT:REF /OPT:ICF"

      - name: Archive
        uses: actions/upload-artifact@v5
        with:
          name: curl_${{ runner.os }}
          path: |
            curl/builds/
